# Generated by Django 3.1.3 on 2021-01-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ports',
            fields=[
                ('code', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'ports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('day', models.DateField()),
                ('price', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'prices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('slug', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'regions',
                'managed': False,
            },
        ),
    ]
